map:
  border_size: 1500
  warzone_radius: 500
  default_balance: 250
  claim_balance_multiplier: 12
  block_operation_speed: 10
  faction:
    faction_sizes: 4
    allies: 0
kitmap:
  kitmap_enabled: true
enchant_limiter:
  sharpness: 1
  protection: 1